'use client'

import { DocumentTextIcon, ArrowDownTrayIcon } from '@heroicons/react/24/outline'

interface ESGReportPreviewProps {
  companyName: string
  projectTitle: string
  grantAmount: number
  organizationName: string
  sdgGoals: string[]
  impactDescription?: string
  photos?: string[]
}

export default function ESGReportPreview({
  companyName,
  projectTitle,
  grantAmount,
  organizationName,
  sdgGoals,
  impactDescription = "Projektet nådde 250 ungdomar i Stockholmsområdet genom 12 fotbollsträningar och 3 turneringar. Deltagarna rapporterade ökad fysisk aktivitet (85%) och nya vänskap (92%). Projektet bidrog till social inkludering och minskad ungdomsensamhet i förorten.",
  photos = []
}: ESGReportPreviewProps) {
  const currentDate = new Date().toLocaleDateString('sv-SE', { year: 'numeric', month: 'long', day: 'numeric' })

  return (
    <div className="bg-white rounded-xl shadow-lg border-2 border-gray-200 overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-teal-600 to-teal-700 p-6 text-white">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h2 className="text-2xl font-bold">ESG Impact Report</h2>
            <p className="text-teal-100 text-sm mt-1">Generated by Kollektivly</p>
          </div>
          <DocumentTextIcon className="w-12 h-12 text-teal-200" />
        </div>
        <div className="text-sm text-teal-100">
          Rapport genererad: {currentDate}
        </div>
      </div>

      {/* Preview Content */}
      <div className="p-8 space-y-8">
        {/* Company & Project */}
        <div>
          <h3 className="text-lg font-bold text-gray-900 mb-4 pb-2 border-b-2 border-gray-200">
            Företagsinformation
          </h3>
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <span className="text-gray-600">Företag:</span>
              <div className="font-semibold text-gray-900">{companyName}</div>
            </div>
            <div>
              <span className="text-gray-600">Bidragsbelopp:</span>
              <div className="font-semibold text-green-600">{grantAmount.toLocaleString('sv-SE')} SEK</div>
            </div>
            <div>
              <span className="text-gray-600">Samarbetspartner:</span>
              <div className="font-semibold text-gray-900">{organizationName}</div>
            </div>
            <div>
              <span className="text-gray-600">Projekt:</span>
              <div className="font-semibold text-gray-900">{projectTitle}</div>
            </div>
          </div>
        </div>

        {/* SDG Goals */}
        <div>
          <h3 className="text-lg font-bold text-gray-900 mb-4 pb-2 border-b-2 border-gray-200">
            FN:s globala mål (SDG)
          </h3>
          <div className="flex flex-wrap gap-3">
            {sdgGoals.map((goal, idx) => (
              <div
                key={idx}
                className="px-4 py-2 bg-blue-100 text-blue-900 rounded-lg text-sm font-semibold border-2 border-blue-200"
              >
                {goal}
              </div>
            ))}
          </div>
          <p className="text-sm text-gray-600 mt-4">
            Detta projekt adresserar {sdgGoals.length} av FN:s 17 globala mål för hållbar utveckling.
          </p>
        </div>

        {/* Impact Metrics */}
        <div>
          <h3 className="text-lg font-bold text-gray-900 mb-4 pb-2 border-b-2 border-gray-200">
            Impact Summary
          </h3>
          <div className="bg-teal-50 p-6 rounded-lg border border-teal-200">
            <p className="text-gray-800 leading-relaxed">{impactDescription}</p>
          </div>

          <div className="grid grid-cols-3 gap-4 mt-6">
            <div className="bg-gradient-to-br from-blue-50 to-blue-100 p-4 rounded-lg border border-blue-200 text-center">
              <div className="text-3xl font-bold text-blue-600">250</div>
              <div className="text-sm text-gray-700 mt-1">Personer nådda</div>
            </div>
            <div className="bg-gradient-to-br from-green-50 to-green-100 p-4 rounded-lg border border-green-200 text-center">
              <div className="text-3xl font-bold text-green-600">92%</div>
              <div className="text-sm text-gray-700 mt-1">Positiv feedback</div>
            </div>
            <div className="bg-gradient-to-br from-purple-50 to-purple-100 p-4 rounded-lg border border-purple-200 text-center">
              <div className="text-3xl font-bold text-purple-600">15</div>
              <div className="text-sm text-gray-700 mt-1">Veckor genomförande</div>
            </div>
          </div>
        </div>

        {/* Verification Status */}
        <div>
          <h3 className="text-lg font-bold text-gray-900 mb-4 pb-2 border-b-2 border-gray-200">
            Verifieringsstatus
          </h3>
          <div className="space-y-3">
            <div className="flex items-center gap-3 p-3 bg-green-50 rounded-lg border border-green-200">
              <div className="w-8 h-8 bg-green-500 rounded-full flex items-center justify-center flex-shrink-0">
                <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <div className="flex-1">
                <div className="font-semibold text-gray-900">Legitimitetskontroll godkänd</div>
                <div className="text-sm text-gray-600">Stadgar och årsredovisning verifierad av AI (Confidence: 94%)</div>
              </div>
            </div>

            <div className="flex items-center gap-3 p-3 bg-green-50 rounded-lg border border-green-200">
              <div className="w-8 h-8 bg-green-500 rounded-full flex items-center justify-center flex-shrink-0">
                <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <div className="flex-1">
                <div className="font-semibold text-gray-900">Impact-rapportering godkänd</div>
                <div className="text-sm text-gray-600">Rapport, bilder och sociala medier verifierad (Confidence: 89%)</div>
              </div>
            </div>
          </div>
        </div>

        {/* Timeline */}
        <div>
          <h3 className="text-lg font-bold text-gray-900 mb-4 pb-2 border-b-2 border-gray-200">
            Projekttidslinje
          </h3>
          <div className="space-y-4">
            <div className="flex gap-4">
              <div className="flex flex-col items-center">
                <div className="w-10 h-10 bg-teal-600 rounded-full flex items-center justify-center text-white font-bold">
                  1
                </div>
                <div className="w-0.5 h-full bg-teal-300 mt-2"></div>
              </div>
              <div className="pb-8">
                <div className="font-semibold text-gray-900">Betalning initierad</div>
                <div className="text-sm text-gray-600">1 mars 2025 • {grantAmount.toLocaleString('sv-SE')} SEK</div>
              </div>
            </div>

            <div className="flex gap-4">
              <div className="flex flex-col items-center">
                <div className="w-10 h-10 bg-teal-600 rounded-full flex items-center justify-center text-white font-bold">
                  2
                </div>
                <div className="w-0.5 h-full bg-teal-300 mt-2"></div>
              </div>
              <div className="pb-8">
                <div className="font-semibold text-gray-900">Milstolpe 1 godkänd</div>
                <div className="text-sm text-gray-600">15 mars 2025 • {(grantAmount / 2).toLocaleString('sv-SE')} SEK utbetalt</div>
              </div>
            </div>

            <div className="flex gap-4">
              <div className="flex flex-col items-center">
                <div className="w-10 h-10 bg-teal-600 rounded-full flex items-center justify-center text-white font-bold">
                  3
                </div>
              </div>
              <div>
                <div className="font-semibold text-gray-900">Milstolpe 2 godkänd</div>
                <div className="text-sm text-gray-600">30 maj 2025 • {(grantAmount / 2).toLocaleString('sv-SE')} SEK utbetalt</div>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="border-t-2 border-gray-200 pt-6">
          <div className="flex items-center justify-between">
            <div className="text-sm text-gray-600">
              <p>Genererad av Kollektivly AI-verifieringssystem</p>
              <p className="mt-1">Rapport-ID: ESG-{Math.random().toString(36).substring(2, 10).toUpperCase()}</p>
            </div>
            <div className="text-right text-sm text-gray-600">
              <p>CSRD-kompatibel</p>
              <p className="mt-1">SDG-aligned</p>
            </div>
          </div>
        </div>
      </div>

      {/* Download CTA */}
      <div className="bg-gray-50 px-8 py-6 border-t-2 border-gray-200">
        <div className="flex items-center justify-between">
          <div>
            <p className="font-semibold text-gray-900">ESG-rapport inkluderad i Standard & Enhanced tiers</p>
            <p className="text-sm text-gray-600 mt-1">PDF-format, direkt nedladdningsbar när projektet är slutfört</p>
          </div>
          <button
            disabled
            className="flex items-center gap-2 px-6 py-3 bg-gray-300 text-gray-500 rounded-lg font-medium cursor-not-allowed"
          >
            <ArrowDownTrayIcon className="w-5 h-5" />
            Ladda ner PDF
          </button>
        </div>
      </div>
    </div>
  )
}